apiVersion: v1
kind: Service
metadata:
  name: dropzone-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: dropzone-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dropzone-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dropzone-demo
  template:
    metadata:
      labels:
        app: dropzone-demo
    spec:
      securityContext:
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: dropzone-demo
        image: ashwilliams/dropzone-demo:v2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: images-persistent-storage2
          mountPath: /var/www/html/images
      volumes:
      - name: images-persistent-storage2
        persistentVolumeClaim:
          claimName: images-persistent-storage2