apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-persistent-storage2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi